import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../models/user.dart';
import '../repositories/sqlite_user_repository.dart';
import '../repositories/user_repository.dart';

part 'user_view_model.g.dart';

class UserState {
  final List<UserModel> items;
  final bool isLoading;

  const UserState({
    this.items = const <UserModel>[],
    this.isLoading = false,
  });

  UserState copyWith({
    List<UserModel>? items,
    bool? isLoading,
  }) {
    return UserState(
      items: items ?? this.items,
      isLoading: isLoading ?? this.isLoading,
    );
  }
}

@riverpod
UserRepository userRepository(UserRepositoryRef ref) {
  return SqliteUserRepository();
}

@riverpod
class UserViewModel extends _$UserViewModel {
  @override
  UserState build() {
    loadUsers();
    return const UserState(isLoading: true);
  }

  UserRepository get _repository => ref.read(userRepositoryProvider);

  Future<void> loadUsers() async {
    state = state.copyWith(isLoading: true);
    final users = await _repository.getUsers();
    state = state.copyWith(items: users, isLoading: false);
  }

  Future<void> addUser({
    required String fullName,
    required String email,
    required String avatar,
  }) async {
    final newUser = UserModel(
      id: 0, // id will be generated by SQLite AUTOINCREMENT
      fullName: fullName,
      email: email,
      avatar: avatar,
    );
    await _repository.addUser(newUser);
    await loadUsers(); // Reload để lấy danh sách với ID thực từ SQLite
  }

  Future<void> updateUser(UserModel user) async {
    await _repository.updateUser(user);
    final updatedItems = state.items.map((e) => e.id == user.id ? user : e).toList();
    state = state.copyWith(items: updatedItems);
  }

  Future<void> deleteUser(int id) async {
    await _repository.deleteUser(id);
    final updatedItems = state.items.where((e) => e.id != id).toList();
    state = state.copyWith(items: updatedItems);
  }
}
